#Docker Compose for development
version: '3.5'
services:
  app_db:
    image: amazon/dynamodb-local:1.18.0
    container_name: app_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: app
    networks: [app]
    ports:
      - 3636:8000
  app_test:
   image: golang:1.18
   container_name: app_test
   environment:
     #DB CONFIGURATION
     PORT: 8000
     DYNAMODB: http://app_db:8000
     AWS_ACCESS_KEY_ID: "example"
     AWS_SECRET_ACCESS_KEY: "example"
   volumes:
     - type: bind
       source: .
       target: /app
   depends_on:
     - app_db
   networks: [app]
   working_dir: /app
   entrypoint: "go test ./..."
  app:
   image: app_go
   container_name: app
   build:
    context: .
    dockerfile: Dockerfile
   environment:
     #DB CONFIGURATION
     PORT: 8000
     DYNAMODB: http://app_db:8000
     AWS_ACCESS_KEY_ID: "example"
     AWS_SECRET_ACCESS_KEY: "example"
   depends_on:
     - app_db
   networks: [app]
   ports:
      - 8000:8000

networks:
  app:
    name: app
    driver: bridge
